name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    unit_tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php:
                    - 8.1
                extensions:
                    - none, ext-dom, mbstring, curl, pcntl
                    - none, ext-dom, mbstring, curl

        name: PHP ${{ matrix.php }} tests

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov
                    extensions:  ${{ matrix.extensions }}

            -   uses: "ramsey/composer-install@v2"

            -   run: make tests

            -   uses: codecov/codecov-action@v2
                with:
                    name: "phpunit-php${{ matrix.php-version }}"
                    flags: phpunit
                    fail_ci_if_error: true
                continue-on-error: true
